CREATE DATABASE airflow;
CREATE DATABASE metastore;
CREATE USER airflow WITH ENCRYPTED PASSWORD 'airflow';
CREATE USER hive WITH ENCRYPTED PASSWORD 'hive';
GRANT ALL PRIVILEGES ON DATABASE airflow TO airflow;
GRANT ALL PRIVILEGES ON DATABASE metastore TO hive;
